from __future__ import annotations

"""PostgreSQL 16 implementation of the FAAR store contract.

The state-machine implementation lives in :mod:`faar.store`.  This backend
supplies the same DB-API surface while replacing SQLite's global
``BEGIN IMMEDIATE`` writer lock with a transaction-scoped PostgreSQL advisory
lock.  That deliberately conservative lock preserves the reference store's
linearization order for aggregate budgets, authority changes, permits, intent
CAS operations, and evidence appends across hosts.

No connection string is included in diagnostics: production DSNs commonly
contain credentials and must be supplied by the deployment's secret channel.
"""

import hashlib
import os
import re
import socket
import sqlite3
import threading
import uuid
from contextlib import contextmanager
from typing import Any, Iterator

from .anchor import AuthorityAnchor
from .store import (
    STORE_SCHEMA_REVISION,
    LeaseOwnerAlive,
    MigrationError,
    SQLiteIntentStore,
    StoreUnavailable,
)


_SCHEMA_RE = re.compile(r"[a-z][a-z0-9_]{0,62}\Z")
POSTGRES_SCHEMA_REVISION = STORE_SCHEMA_REVISION + "-pg1"
POSTGRES_BACKEND_ID = "postgresql16"


_POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS grants (
    grant_id TEXT NOT NULL,
    version BIGINT NOT NULL,
    principal_id TEXT NOT NULL,
    grant_hash TEXT NOT NULL,
    grant_json TEXT NOT NULL,
    runtime_status TEXT NOT NULL CHECK(runtime_status IN ('ACTIVE','PAUSED','REVOKED')),
    runtime_epoch BIGINT NOT NULL DEFAULT 1,
    fence_counter BIGINT NOT NULL DEFAULT 0,
    provisioned_at TEXT NOT NULL,
    PRIMARY KEY(grant_id, version)
);
CREATE TABLE IF NOT EXISTS usage_reservations (
    intent_id TEXT PRIMARY KEY,
    principal_id TEXT NOT NULL,
    grant_id TEXT NOT NULL,
    grant_version BIGINT NOT NULL,
    day_key TEXT NOT NULL,
    velocity_bucket BIGINT,
    velocity_ts BIGINT,
    amount_usd TEXT NOT NULL,
    status TEXT NOT NULL CHECK(status IN ('HELD','COMMITTED','RELEASED')),
    submitted INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_usage_grant_day
  ON usage_reservations(grant_id, grant_version, day_key, status);
CREATE INDEX IF NOT EXISTS ix_usage_grant_bucket
  ON usage_reservations(grant_id, grant_version, velocity_bucket, status);
CREATE TABLE IF NOT EXISTS risk_claims (
    principal_id TEXT NOT NULL,
    grant_id TEXT NOT NULL,
    grant_version BIGINT NOT NULL,
    risk_scope TEXT NOT NULL,
    state_version BIGINT NOT NULL,
    intent_id TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL,
    PRIMARY KEY(grant_id, grant_version, risk_scope, state_version)
);
CREATE INDEX IF NOT EXISTS ix_risk_claims_scope
  ON risk_claims(grant_id, grant_version, risk_scope, state_version);
CREATE TABLE IF NOT EXISTS permit_risk_claims (
    principal_id TEXT NOT NULL,
    grant_id TEXT NOT NULL,
    grant_version BIGINT NOT NULL,
    risk_scope TEXT NOT NULL,
    state_version BIGINT NOT NULL,
    intent_id TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY(grant_id, grant_version, risk_scope, state_version)
);
CREATE INDEX IF NOT EXISTS ix_permit_risk_claims_intent
  ON permit_risk_claims(intent_id, grant_id, grant_version);
CREATE TABLE IF NOT EXISTS intents (
    intent_id TEXT PRIMARY KEY,
    principal_id TEXT NOT NULL,
    venue TEXT NOT NULL DEFAULT '',
    intent_hash TEXT NOT NULL,
    state TEXT NOT NULL,
    intent_json TEXT NOT NULL,
    effect_id TEXT,
    reason_codes TEXT NOT NULL DEFAULT '[]',
    submission_count BIGINT NOT NULL DEFAULT 0,
    ambiguity_until TEXT,
    filled_amount_usd TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS intent_leases (
    intent_id TEXT PRIMARY KEY,
    owner_token TEXT NOT NULL,
    acquired_at TEXT NOT NULL,
    host TEXT,
    pid INTEGER
);
CREATE TABLE IF NOT EXISTS evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intent_id TEXT NOT NULL,
    principal_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    prev_hash TEXT,
    event_hash TEXT NOT NULL,
    event_mac TEXT,
    FOREIGN KEY(intent_id) REFERENCES intents(intent_id)
);
CREATE TABLE IF NOT EXISTS evidence_head (
    intent_id TEXT PRIMARY KEY,
    seq BIGINT NOT NULL,
    head_hash TEXT NOT NULL,
    head_mac TEXT,
    updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS runtime_controls (
    scope TEXT PRIMARY KEY,
    halted INTEGER NOT NULL CHECK(halted IN (0,1)),
    reason TEXT,
    control_epoch BIGINT NOT NULL DEFAULT 1,
    updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS execution_permits (
    permit_id TEXT PRIMARY KEY,
    issuance_seq BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    intent_id TEXT NOT NULL,
    principal_id TEXT NOT NULL,
    grant_id TEXT NOT NULL,
    grant_version BIGINT NOT NULL,
    grant_epoch BIGINT NOT NULL,
    fence_token BIGINT NOT NULL,
    permit_hash TEXT NOT NULL,
    issued_at TEXT NOT NULL,
    expires_at TEXT,
    consumed_at TEXT,
    voided_at TEXT,
    UNIQUE(grant_id, grant_version, fence_token)
);
CREATE TABLE IF NOT EXISTS store_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS exposure_caps (
    scope TEXT PRIMARY KEY,
    max_turnover_usd TEXT NOT NULL,
    updated_at TEXT NOT NULL
)
"""


class _EmptyCursor:
    rowcount = 0

    def fetchone(self) -> None:
        return None

    def fetchall(self) -> list[Any]:
        return []


def _postgres_sql(sql: str) -> str:
    """Translate the reference store's narrow SQLite SQL dialect.

    Question marks are replaced only outside quoted SQL literals.  The two
    ``rowid`` references encode permit issuance order and map to the explicit
    PostgreSQL identity column.
    """
    sql = sql.replace("rowid,* FROM execution_permits", "issuance_seq AS rowid,* FROM execution_permits")
    sql = sql.replace("AND rowid > ?", "AND issuance_seq > ?")
    out: list[str] = []
    quoted = False
    index = 0
    while index < len(sql):
        char = sql[index]
        if char == "'":
            out.append(char)
            if quoted and index + 1 < len(sql) and sql[index + 1] == "'":
                out.append("'")
                index += 2
                continue
            quoted = not quoted
        elif char == "?" and not quoted:
            out.append("%s")
        else:
            out.append(char)
        index += 1
    return "".join(out)


class _PostgresConnection:
    """Small compatibility surface used by ``SQLiteIntentStore`` methods."""

    def __init__(self, raw: Any, psycopg_module: Any, writer_lock_name: str) -> None:
        self.raw = raw
        self.psycopg = psycopg_module
        self.writer_lock_name = writer_lock_name

    def _raise_driver_error(self, exc: BaseException) -> None:
        if isinstance(exc, self.psycopg.IntegrityError):
            constraint = getattr(getattr(exc, "diag", None), "constraint_name", None)
            detail = f"{constraint}: {exc}" if constraint else str(exc)
            raise sqlite3.IntegrityError(detail) from exc
        if isinstance(exc, (self.psycopg.OperationalError, self.psycopg.InterfaceError)):
            raise StoreUnavailable("PostgreSQL datastore unavailable") from exc
        if isinstance(exc, self.psycopg.Error):
            raise StoreUnavailable("PostgreSQL datastore operation failed") from exc
        raise exc

    def execute(self, sql: str, params: tuple[Any, ...] | list[Any] = ()) -> Any:
        statement = sql.strip()
        try:
            if statement == "BEGIN IMMEDIATE":
                self.raw.execute("BEGIN")
                try:
                    return self.raw.execute(
                        "SELECT pg_advisory_xact_lock(hashtextextended(%s, 0))",
                        (self.writer_lock_name,),
                    )
                except BaseException:
                    # Acquiring the writer lock happens before inherited methods
                    # enter their try/finally transaction body. Roll back here so a
                    # timeout cannot strand the connection in an aborted txn.
                    try:
                        self.raw.execute("ROLLBACK")
                    except BaseException:
                        pass
                    raise
            if statement == "BEGIN":
                return self.raw.execute("BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY")
            if statement == "ROLLBACK" and self.raw.closed:
                return _EmptyCursor()
            if statement.startswith("PRAGMA "):
                return _EmptyCursor()
            return self.raw.execute(_postgres_sql(sql), params)
        except BaseException as exc:
            # Preserve the original failure if a broken connection cannot accept
            # the cleanup ROLLBACK issued by the inherited transaction body.
            if statement == "ROLLBACK":
                return _EmptyCursor()
            self._raise_driver_error(exc)
            raise AssertionError("unreachable")

    def executescript(self, script: str) -> None:
        self.execute("BEGIN IMMEDIATE")
        try:
            for statement in script.split(";"):
                if statement.strip():
                    self.execute(statement)
            self.execute("COMMIT")
        except BaseException:
            self.execute("ROLLBACK")
            raise

    def close(self) -> None:
        self.raw.close()


class PostgresIntentStore(SQLiteIntentStore):
    """PostgreSQL 16 store reproducing ``STORE_CONTRACT.md`` semantics.

    ``schema`` is an explicit namespace so test and deployment instances cannot
    accidentally share ledgers.  The constructor creates that schema only when
    it is absent; opening a current store performs read-only schema/index probes.
    """

    _POSTGRES_COLUMN_MIGRATIONS = SQLiteIntentStore._COLUMN_MIGRATIONS + (
        ("execution_permits", "issuance_seq", "BIGINT GENERATED BY DEFAULT AS IDENTITY"),
    )
    _POSTGRES_BIGINT_COLUMNS = {
        "grants": {"version", "runtime_epoch", "fence_counter"},
        "usage_reservations": {"grant_version", "velocity_bucket", "velocity_ts"},
        "risk_claims": {"grant_version", "state_version"},
        "permit_risk_claims": {"grant_version", "state_version"},
        "intents": {"submission_count"},
        "evidence_head": {"seq"},
        "runtime_controls": {"control_epoch"},
        "execution_permits": {"grant_version", "grant_epoch", "fence_token", "issuance_seq"},
    }

    def __init__(
        self,
        dsn: str,
        *,
        schema: str = "faar",
        evidence_key: bytes | None = None,
        authority_anchor: AuthorityAnchor | None = None,
    ) -> None:
        if not isinstance(dsn, str) or not dsn:
            raise ValueError("a PostgreSQL DSN is required")
        if not isinstance(schema, str) or _SCHEMA_RE.fullmatch(schema) is None:
            raise ValueError("PostgreSQL schema must match [a-z][a-z0-9_]{0,62}")
        try:
            import psycopg
            from psycopg import sql as pg_sql
            from psycopg.rows import dict_row
        except ImportError as exc:  # pragma: no cover - exercised without the optional extra
            raise RuntimeError("install faar-runtime[postgres] to use PostgresIntentStore") from exc

        self.path = f"postgresql:<redacted>/{schema}"
        self._dsn = dsn
        self._schema = schema
        self._psycopg = psycopg
        self._pg_sql = pg_sql
        self._anchor = authority_anchor
        self._lock = threading.RLock()
        self._intent_lock_guard = threading.Lock()
        self._intent_locks = {}
        self._intent_guard_local = threading.local()
        self._host = socket.gethostname()
        self._instance_id = uuid.uuid4().hex
        self._evidence_key = bytes(evidence_key) if evidence_key is not None else None
        if self._evidence_key is not None and len(self._evidence_key) < 16:
            raise ValueError("evidence_key must be at least 16 bytes")

        try:
            raw = psycopg.connect(
                dsn,
                autocommit=True,
                row_factory=dict_row,
                connect_timeout=10,
                application_name="faar-runtime",
            )
            raw.execute("SET lock_timeout = '30s'")
            raw.execute("SET statement_timeout = '60s'")
            raw.execute("SET synchronous_commit = on")
            self._ensure_namespace(raw)
            raw.execute(pg_sql.SQL("SET search_path TO {}, public").format(pg_sql.Identifier(schema)))
            database = str(raw.execute("SELECT current_database() AS name").fetchone()["name"])
        except psycopg.Error as exc:
            if "raw" in locals():
                raw.close()
            raise StoreUnavailable("PostgreSQL datastore initialization failed") from exc

        scope_material = f"{database}\x1f{schema}".encode("utf-8")
        self._fence_scope = "postgres:" + hashlib.sha256(scope_material).hexdigest()
        writer_lock_name = f"faar:{database}:{schema}:writer:v1"
        self._conn = _PostgresConnection(raw, psycopg, writer_lock_name)

        try:
            self._migrate_columns()
            self._create_dependent_indexes()
            self._bind_anchor_setting()
            self._bind_heads_since()
        except BaseException:
            raw.close()
            raise

    def _ensure_namespace(self, raw: Any) -> None:
        exists = raw.execute(
            "SELECT 1 FROM pg_namespace WHERE nspname=%s", (self._schema,)
        ).fetchone()
        if exists is not None:
            return
        raw.execute("BEGIN")
        try:
            raw.execute(
                "SELECT pg_advisory_xact_lock(hashtextextended(%s, 0))",
                (f"faar:schema:{self._schema}:v1",),
            )
            raw.execute(
                self._pg_sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(
                    self._pg_sql.Identifier(self._schema)
                )
            )
            raw.execute("COMMIT")
        except BaseException:
            raw.execute("ROLLBACK")
            raise

    def _table_exists(self, table: str) -> bool:
        return self._conn.execute("SELECT to_regclass(%s) AS name", (table,)).fetchone()["name"] is not None

    def _migrate_columns(self) -> None:
        stamped = None
        backend = None
        if self._table_exists("store_settings"):
            stamped = self._conn.execute(
                "SELECT value FROM store_settings WHERE key='schema_revision'"
            ).fetchone()
            backend = self._conn.execute(
                "SELECT value FROM store_settings WHERE key='backend'"
            ).fetchone()
        if (
            stamped is not None
            and str(stamped["value"]) == POSTGRES_SCHEMA_REVISION
            and backend is not None
            and str(backend["value"]) == POSTGRES_BACKEND_ID
        ):
            return

        self._conn.execute("BEGIN IMMEDIATE")
        try:
            for statement in _POSTGRES_SCHEMA.split(";"):
                if statement.strip():
                    self._conn.execute(statement)
            for table, column, definition in self._POSTGRES_COLUMN_MIGRATIONS:
                present = self._conn.execute(
                    "SELECT 1 FROM information_schema.columns "
                    "WHERE table_schema=current_schema() AND table_name=? AND column_name=?",
                    (table, column),
                ).fetchone()
                if present is None:
                    # Identifiers and definitions are compile-time constants above.
                    self._conn.execute(f"ALTER TABLE {table} ADD COLUMN {column} {definition}")
            for table, columns in self._POSTGRES_BIGINT_COLUMNS.items():
                for column in columns:
                    kind = self._conn.execute(
                        "SELECT data_type FROM information_schema.columns "
                        "WHERE table_schema=current_schema() AND table_name=? AND column_name=?",
                        (table, column),
                    ).fetchone()
                    if kind is not None and str(kind["data_type"]) != "bigint":
                        self._conn.execute(
                            f"ALTER TABLE {table} ALTER COLUMN {column} TYPE BIGINT"
                        )
            self._backfill_legacy_rows_locked()
            self._create_dependent_indexes_locked()
            existing_backend = self._conn.execute(
                "SELECT value FROM store_settings WHERE key='backend'"
            ).fetchone()
            if existing_backend is not None and str(existing_backend["value"]) != POSTGRES_BACKEND_ID:
                raise MigrationError("store_settings.backend is not postgresql16")
            if existing_backend is None:
                self._conn.execute(
                    "INSERT INTO store_settings(key,value,updated_at) VALUES('backend',?,?)",
                    (POSTGRES_BACKEND_ID, self._now()),
                )
            self._conn.execute(
                "INSERT INTO store_settings(key,value,updated_at) VALUES('schema_revision',?,?) "
                "ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at",
                (POSTGRES_SCHEMA_REVISION, self._now()),
            )
            self._conn.execute("COMMIT")
        except BaseException as exc:
            self._conn.execute("ROLLBACK")
            if isinstance(exc, (sqlite3.IntegrityError, StoreUnavailable, MigrationError)):
                raise
            raise MigrationError("PostgreSQL schema migration failed") from exc

    def _create_dependent_indexes(self) -> None:
        expected = {
            "ix_usage_grant_velocity_ts",
            "ix_usage_principal_velocity_ts",
            "ix_evidence_intent_id",
            "ix_permits_intent",
            "ix_usage_velocity_status",
            "ux_effect_id_per_venue",
            "ux_execution_permits_issuance_seq",
        }
        rows = self._conn.execute(
            "SELECT indexname AS name FROM pg_indexes WHERE schemaname=current_schema()"
        ).fetchall()
        if expected.issubset({str(row["name"]) for row in rows}):
            return
        self._conn.execute("BEGIN IMMEDIATE")
        try:
            self._create_dependent_indexes_locked()
            self._conn.execute("COMMIT")
        except BaseException:
            self._conn.execute("ROLLBACK")
            raise

    def _create_dependent_indexes_locked(self) -> None:
        super()._create_dependent_indexes_locked()
        self._conn.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS ux_execution_permits_issuance_seq "
            "ON execution_permits(issuance_seq)"
        )

    @contextmanager
    def execution_guard(self, grant_id: str, version: int) -> Iterator[None]:
        """Serialize local submitters without blocking cross-host emergency stops.

        Cross-host ordering is provided by the transaction lock plus the durable
        grant epoch checked by permit consumption.  Holding a database/session lock
        across an external adapter call would let a hung venue block revocation.
        """
        lock = self._grant_lock(grant_id, version)
        with lock:
            yield

    def clear_stale_intent_lease(
        self,
        intent_id: str,
        *,
        expected_owner_token: str,
        force: bool = False,
    ) -> bool:
        with self._lock:
            self._conn.execute("BEGIN IMMEDIATE")
            try:
                row = self._conn.execute(
                    "SELECT owner_token,host,pid FROM intent_leases WHERE intent_id=?",
                    (intent_id,),
                ).fetchone()
                if row is None or str(row["owner_token"]) != expected_owner_token:
                    self._conn.execute("COMMIT")
                    return False
                if (
                    not force
                    and row["pid"] is not None
                    and row["host"] == self._host
                    and self._pid_alive(row["pid"])
                ):
                    raise LeaseOwnerAlive(
                        f"lease for {intent_id} is held by live process {row['pid']} "
                        f"on {row['host']}; refuse unless forced"
                    )
                deleted = self._conn.execute(
                    "DELETE FROM intent_leases WHERE intent_id=? AND owner_token=?",
                    (intent_id, expected_owner_token),
                ).rowcount == 1
                self._conn.execute("COMMIT")
                return deleted
            except BaseException:
                self._conn.execute("ROLLBACK")
                raise

    def checkpoint(self, *, attempts: int = 10) -> bool:
        """Confirm connectivity; PostgreSQL backup/WAL management is external.

        PostgreSQL commits use ``synchronous_commit=on`` on this connection.  This
        method is not an instruction to copy database files and does not replace a
        managed backup/failover procedure.
        """
        del attempts
        with self._lock:
            self._conn.execute("SELECT 1").fetchone()
        return True


__all__ = ["POSTGRES_SCHEMA_REVISION", "PostgresIntentStore"]
